idf_component_register(
    SRCS 
        "main.cpp"
        "display/oled_driver.cpp"
        "display/face_engine.cpp"
        "audio/audio_player.cpp"
    INCLUDE_DIRS 
        "." 
        "display" 
        "audio"
    REQUIRES 
        driver 
        esp_driver_i2c 
        esp_driver_i2s 
        esp_timer 
        freertos 
        log 
        esp_psram 
        esp_system 
        spi_flash
)
