idf_component_register(
    SRCS 
        "main.cpp"
        "core/robot_brain.cpp"
        "display/oled_driver.cpp"
        "display/face_engine.cpp"
        "display/display_service.cpp"
        "audio/audio_player.cpp"
        "audio/audio_recorder.cpp"
        "audio/audio_service.cpp"
        "comm/uart_comm.cpp"
        "comm/protocol_parser.cpp"
        "comm/motion_service.cpp"
    INCLUDE_DIRS 
        "." 
        "core"
        "display" 
        "audio" 
        "comm"
    REQUIRES 
        driver 
        esp_driver_i2c 
        esp_driver_i2s 
        esp_driver_uart
        esp_timer 
        freertos 
        log 
        esp_psram 
        esp_system 
        spi_flash
)
